DROP TABLE IF EXISTS user_table;
CREATE TABLE  user_table(
   id INT PRIMARY KEY, 
   user_name VARCHAR(100) NOT NULL,
   email VARCHAR(255) NOT NULL, 
   password VARCHAR(255) NOT NULL,
   about VARCHAR(255) DEFAULT NULL
 );